# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/rockchip/rk2918/setup-makefiles.sh

#libs
PRODUCT_COPY_FILES += \
  vendor/rockchip/rk2918/proprietary/lib/libGAL.so:system/lib/libGAL.so \
  vendor/rockchip/rk2918/proprietary/lib/libGLSLC.so:system/lib/libGLSLC.so \
  vendor/rockchip/rk2918/proprietary/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
  vendor/rockchip/rk2918/proprietary/lib/libUMP.so:system/lib/libUMP.so \
  vendor/rockchip/rk2918/proprietary/lib/libapedec.so:system/lib/libapedec.so \
  vendor/rockchip/rk2918/proprietary/lib/libhtml5_check.so:system/lib/libhtml5_check.so \
  vendor/rockchip/rk2918/proprietary/lib/libion.so:system/lib/libion.so \
  vendor/rockchip/rk2918/proprietary/lib/libjpeghwdec.so:system/lib/libjpeghwdec.so \
  vendor/rockchip/rk2918/proprietary/lib/libjpeghwenc.so:system/lib/libjpeghwenc.so \
  vendor/rockchip/rk2918/proprietary/lib/libomxvpu.so:system/lib/libomxvpu.so \
  vendor/rockchip/rk2918/proprietary/lib/libomxvpu_enc.so:system/lib/libomxvpu_enc.so \
  vendor/rockchip/rk2918/proprietary/lib/libril-rk29-dataonly.so:system/lib/libril-rk29-dataonly.so \
  vendor/rockchip/rk2918/proprietary/lib/librkswscale.so:system/lib/librkswscale.so \
  vendor/rockchip/rk2918/proprietary/lib/librkwmapro.so:system/lib/librkwmapro.so \
  vendor/rockchip/rk2918/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
  vendor/rockchip/rk2918/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
  vendor/rockchip/rk2918/proprietary/lib/libvpu.so:system/lib/libvpu.so \
  vendor/rockchip/rk2918/proprietary/lib/libyuvtorgb.so:system/lib/libyuvtorgb.so \
  vendor/rockchip/rk2918/proprietary/lib/registry:system/lib/registry \
  
#vendor/rockchip/rk2918/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so
#vendor/rockchip/rk2918/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
#vendor/rockchip/rk2918/proprietary/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \

#usb firms
PRODUCT_COPY_FILES += \
  vendor/rockchip/rk2918/proprietary/etc/firmware/athtcmd_ram.bin:system/etc/firmware/athtcmd_ram.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/athwlan.bin.z77:system/etc/firmware/athwlan.bin.z77 \
  vendor/rockchip/rk2918/proprietary/etc/firmware/bdata.SD31.bin:system/etc/firmware/bdata.SD31.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/data.patch.hw2_0.bin:system/etc/firmware/data.patch.hw2_0.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/device.bin:system/etc/firmware/device.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_RK901.bin:system/etc/firmware/fw_RK901.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_RK903.bin:system/etc/firmware/fw_RK903.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_RK903_p2p.bin:system/etc/firmware/fw_RK903_p2p.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4319.bin:system/etc/firmware/fw_bcm4319.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4329_wapi.bin:system/etc/firmware/fw_bcm4329_wapi.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4330.bin:system/etc/firmware/fw_bcm4330.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4330_apsta.bin:system/etc/firmware/fw_bcm4330_apsta.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram.txt:system/etc/firmware/nvram.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_4330.txt:system/etc/firmware/nvram_4330.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_RK901.txt:system/etc/firmware/nvram_RK901.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_RK903.cal:system/etc/firmware/nvram_RK903.cal \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_RK903.txt:system/etc/firmware/nvram_RK903.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_RK903_26M.cal:system/etc/firmware/nvram_RK903_26M.cal \
  vendor/rockchip/rk2918/proprietary/etc/firmware/otp.bin.z77:system/etc/firmware/otp.bin.z77 \
  vendor/rockchip/rk2918/proprietary/etc/firmware/sd8686.bin:system/etc/firmware/sd8686.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin \


#Hal 
PRODUCT_COPY_FILES += \
  vendor/rockchip/rk2918/proprietary/lib/hw/audio.primary.rk29board.so:system/lib/hw/audio.primary.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/audio_policy.rk29board.so:system/lib/hw/audio_policy.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/camera.rk29board.so:system/lib/hw/camera.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/copybit.rk29board.so:system/lib/hw/copybit.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/gralloc.rk29board.so:system/lib/hw/gralloc.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/lights.rk29board.so:system/lib/hw/lights.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/sensors.rk29board.so:system/lib/hw/sensors.rk29board.so \
#EGL 
PRODUCT_COPY_FILES += \
  vendor/rockchip/rk2918/proprietary/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
  vendor/rockchip/rk2918/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
  vendor/rockchip/rk2918/proprietary/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
  vendor/rockchip/rk2918/proprietary/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
#Bin
PRODUCT_COPY_FILES += \
  vendor/rockchip/rk2918/proprietary/bin/akmd8975:system/bin/akmd8975 \
  vendor/rockchip/rk2918/proprietary/bin/fsck.exfat:system/bin/fsck.exfat \
  vendor/rockchip/rk2918/proprietary/bin/hostapd_rtl:system/bin/hostapd_rtl \
  vendor/rockchip/rk2918/proprietary/bin/mkfs.exfat:system/bin/mkfs.exfat \
  vendor/rockchip/rk2918/proprietary/bin/mkntfs:system/bin/mkntfs \
  vendor/rockchip/rk2918/proprietary/bin/mount.exfat:system/bin/mount.exfat \
  vendor/rockchip/rk2918/proprietary/bin/ntfs-3g:system/bin/ntfs-3g \
  vendor/rockchip/rk2918/proprietary/bin/ntfs-3g.probe:system/bin/ntfs-3g.probe \
  vendor/rockchip/rk2918/proprietary/bin/performance:system/bin/performance \
  vendor/rockchip/rk2918/proprietary/bin/vdc:system/bin/vdc \
  vendor/rockchip/rk2918/proprietary/bin/surfaceflinger:system/bin/surfaceflinger \
  vendor/rockchip/rk2918/proprietary/bin/vold:system/bin/vold
