# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/rockchip/rk2918/setup-makefiles.sh


PRODUCT_COPY_FILES += \
  vendor/rockchip/rk2918/proprietary/lib/libGAL.so:system/lib/libGAL.so \
  vendor/rockchip/rk2918/proprietary/lib/libGLSLC.so:system/lib/libGLSLC.so \
  vendor/rockchip/rk2918/proprietary/lib/libril-rk29-dataonly.so:system/lib/libril-rk29-dataonly.so \
  vendor/rockchip/rk2918/proprietary/lib/librkswscale.so:system/lib/librkswscale.so \
  vendor/rockchip/rk2918/proprietary/lib/librkwmapro.so:system/lib/librkwmapro.so \
  vendor/rockchip/rk2918/proprietary/lib/registry:system/lib/registry \
  vendor/rockchip/rk2918/proprietary/lib/webkit_ver:system/lib/webkit_ver \
  vendor/rockchip/rk2918/proprietary/etc/firmware/ath3k-1.fw:system/etc/firmware/ath3k-1.fw \
  vendor/rockchip/rk2918/proprietary/etc/firmware/athtcmd_ram.bin:system/etc/firmware/athtcmd_ram.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/athwlan.bin.z77:system/etc/firmware/athwlan.bin.z77 \
  vendor/rockchip/rk2918/proprietary/etc/firmware/bdata.SD31.bin:system/etc/firmware/bdata.SD31.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/data.patch.hw2_0.bin:system/etc/firmware/data.patch.hw2_0.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/device.bin:system/etc/firmware/device.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_RK901.bin:system/etc/firmware/fw_RK901.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_RK903.bin:system/etc/firmware/fw_RK903.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4319.bin:system/etc/firmware/fw_bcm4319.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4329_wapi.bin:system/etc/firmware/fw_bcm4329_wapi.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4330.bin:system/etc/firmware/fw_bcm4330.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/fw_bcm4330_apsta.bin:system/etc/firmware/fw_bcm4330_apsta.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram.txt:system/etc/firmware/nvram.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_4330.txt:system/etc/firmware/nvram_4330.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_RK901.txt:system/etc/firmware/nvram_RK901.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/nvram_RK903.txt:system/etc/firmware/nvram_RK903.txt \
  vendor/rockchip/rk2918/proprietary/etc/firmware/otp.bin.z77:system/etc/firmware/otp.bin.z77 \
  vendor/rockchip/rk2918/proprietary/etc/firmware/sd8686.bin:system/etc/firmware/sd8686.bin \
  vendor/rockchip/rk2918/proprietary/etc/firmware/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin \
  vendor/rockchip/rk2918/proprietary/lib/hw/camera.rk29board.so:system/lib/hw/camera.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/copybit.rk29board.so:system/lib/hw/copybit.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/gralloc.rk29board.so:system/lib/hw/gralloc.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/hw/lights.rk29board.so:system/lib/hw/lights.rk29board.so \
  vendor/rockchip/rk2918/proprietary/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
  vendor/rockchip/rk2918/proprietary/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
  vendor/rockchip/rk2918/proprietary/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
  vendor/rockchip/rk2918/proprietary/bin/fsck.exfat:system/bin/fsck.exfat \
  vendor/rockchip/rk2918/proprietary/bin/hostapd_rtl:system/bin/hostapd_rtl \
  vendor/rockchip/rk2918/proprietary/bin/mkfs.exfat:system/bin/mkfs.exfat \
  vendor/rockchip/rk2918/proprietary/bin/mkntfs:system/bin/mkntfs \
  vendor/rockchip/rk2918/proprietary/bin/mount.exfat:system/bin/mount.exfat \
  vendor/rockchip/rk2918/proprietary/bin/ntfs-3g:system/bin/ntfs-3g \
  vendor/rockchip/rk2918/proprietary/bin/ntfs-3g.probe:system/bin/ntfs-3g.probe \
  vendor/rockchip/rk2918/proprietary/bin/vold:system/bin/vold \

